#ifndef H_FIO_APP_FIO
#define H_FIO_APP_FIO

#include "common.h"

// Just a trick to make the numbers readable
#define __CONCAT4(A,B,C,D) A ## B ## C ## D

/*#define LOVELACE_MAX_SUPPLY (__CONCAT4(45, 000, 000, 000) * 1000000)
#define LOVELACE_INVALID    (__CONCAT4(47, 000, 000, 000) * 1000000)

STATIC_ASSERT(LOVELACE_MAX_SUPPLY < LOVELACE_INVALID, "bad LOVELACE_INVALID");*/

/*#define ADDRESS_KEY_HASH_LENGTH 28
#define POOL_KEY_HASH_LENGTH 28
#define VRF_KEY_HASH_LENGTH 32
#define TX_HASH_LENGTH 32
#define AUX_DATA_HASH_LENGTH 32
#define POOL_METADATA_HASH_LENGTH 32
#define ED25519_SIGNATURE_LENGTH 64

#define MINTING_POLICY_ID_SIZE 28
#define ASSET_NAME_SIZE_MAX 32

#define REWARD_ACCOUNT_SIZE (1 + ADDRESS_KEY_HASH_LENGTH)*/

#define MAX_ADDRESS_SIZE 128
#define MAX_HUMAN_ADDRESS_SIZE 150
#define MAX_HUMAN_REWARD_ACCOUNT_SIZE 65

#define MAINNET_NETWORK_ID 1

#define TESTNET_NETWORK_ID 0

#endif // H_CARDANO_APP_CARDANO
